---
- src: https://github.com/redhat-cop/openshift-applier
  version: master

# The git repository for this project
- src: https://github.com/mmuir@redhat.com/openshift-gitops-lab.git
  name: self
  version: master
